apiVersion: v2
name: rmf-argocd
description: A Helm to configure the argcod in RMF server deployments
type: application
version: 0.1.0

dependencies:
- name: argo-cd
  version: 5.19.15
  repository: https://argoproj.github.io/argo-helm
