argo-cd:
  configs:
    params:
      server.insecure: true
  server:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      https: true
      hosts:
        - argocd.rmf-deployment-template.open-rmf.org
      paths:
        - /
      pathType: Prefix
