harbor:
  expose:
    type: ingress
    tls:
      enabled: false
    ingress:
      hosts:
        core: harbor.rmf-deployment-template.open-rmf.org
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
